# Generated by Django 2.0.2 on 2018-03-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='friends',
            field=models.ManyToManyField(null=True, related_name='_person_friends_+', to='person.Person'),
        ),
    ]
