# Generated by Django 2.0.2 on 2018-03-18 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20180318_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='person_id',
        ),
    ]
